- name: Build KSP Debug
        script: |
          echo "--- Running KSP Debug ---"
          mkdir -p app/schemas
          chmod -R u+w app/schemas
          # Das --info Flag wurde hinzugefügt, um detailliertere Logs zu erhalten
          ./gradlew :app:kspDebugKotlin --stacktrace --info --no-daemon
          if [ $? -ne 0 ]; then
            echo "KSP Debug task failed. See logs above."
            exit 1
          fi
          echo "KSP Debug completed. Verifying schema files."
          # Überprüfe den Inhalt des schemas-Ordners explizit
          echo "Contents of app/schemas/ before artifact collection:"
          ls -la app/schemas/
          if [ -f "app/schemas/1.json" ]; then
            echo "1.json FOUND in app/schemas/"
          else
            echo "1.json NOT FOUND in app/schemas/"
          fi
          # Überprüfe auch den generierten KSP-Output-Ordner
          echo "Contents of app/build/generated/ksp/debug/java/com/MaFiSoft/BuyPal/:"
          ls -la app/build/generated/ksp/debug/java/com/MaFiSoft/BuyPal/ || echo "KSP output folder not found or empty."
          find app/build/generated/ksp/debug/ -type f || echo "No KSP generated files found."
