workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      java: 17
      groups:
        - android_signing
      vars:
        GRADLE_TASK: ":app:assembleRelease"
        ANDROID_KEYSTORE_PATH: "/tmp/keystore.keystore"
        ANDROID_KEYSTORE_PASSWORD: "your_keystore_password"
        ANDROID_KEY_ALIAS: "your_key_alias"
        ANDROID_KEY_PASSWORD: "your_key_password"
    scripts:
      - name: Set executable permissions for gradlew
        script: |
          chmod +x gradlew
      - name: Validate gradlew syntax
        script: |
          bash -n gradlew || exit 1
      - name: Initialize Gradle Wrapper
        script: |
          ./gradlew wrapper --gradle-version 8.4 || echo "Wrapper initialization failed, continuing with existing wrapper"
      - name: Install dependencies
        script: |
          ./gradlew dependencies
      - name: Generate Room Schema
        script: |
          ./gradlew :app:kspDebugKotlin
      - name: Build Android
        script: |
          ./gradlew $GRADLE_TASK
    artifacts:
      - app/build/outputs/**/*.apk
      - app/schemas/**/1.json
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
