workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      java: 17
      groups:
        - android_signing
      vars:
        GRADLE_TASK: ":app:assembleRelease"
        ANDROID_KEYSTORE_PATH: "/tmp/keystore.keystore"
        ANDROID_KEYSTORE_PASSWORD: "your_keystore_password"
        ANDROID_KEY_ALIAS: "your_key_alias"
        ANDROID_KEY_PASSWORD: "your_key_password"
    scripts:
      - name: Check Java version
        script: |
          echo "Checking Java version..."
          java -version
      - name: Verify gradlew exists
        script: |
          echo "Checking if gradlew exists..."
          if [ -f "./gradlew" ]; then
            echo "gradlew found"
          else
            echo "ERROR: gradlew not found" >&2
            exit 1
          fi
      - name: Set executable permissions for gradlew
        script: |
          echo "Setting executable permissions for gradlew..."
          chmod +x gradlew
          ls -l gradlew
      - name: Validate gradlew syntax
        script: |
          echo "Validating gradlew syntax..."
          bash -n gradlew || exit 1
          echo "gradlew syntax is valid"
      - name: Initialize Gradle Wrapper
        script: |
          echo "Initializing Gradle Wrapper for version 8.4..."
          gradle wrapper --gradle-version 8.4
          echo "Verifying gradle-wrapper.jar..."
          if [ -f "gradle/wrapper/gradle-wrapper.jar" ]; then
            echo "gradle-wrapper.jar found, size: $(ls -l gradle/wrapper/gradle-wrapper.jar | awk '{print $5}') bytes"
          else
            echo "ERROR: gradle-wrapper.jar not found" >&2
            exit 1
          fi
      - name: Install dependencies
        script: |
          echo "Installing dependencies..."
          ./gradlew dependencies
      - name: Generate Room Schema
        script: |
          echo "Generating Room schema..."
          ./gradlew :app:kspDebugKotlin
      - name: Build Android
        script: |
          echo "Building Android APK..."
          ./gradlew $GRADLE_TASK
    artifacts:
      - app/build/outputs/**/*.apk
      - app/schemas/**/1.json
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
