# .codemagic.yaml
workflows:
  android-build:
    name: Android Build with KSP & Gradle Wrapper Generation
    instance_type: mac_mini_m1
    
    environment:
      vars:
        ANDROID_SDK_LICENSES: true
        JAVA_TOOL_OPTIONS: -Xmx4096m
    
    triggering:
      branch_patterns:
        - pattern: main
          include: true
          
    scripts:
      - name: Make gradlew executable
        script: |
          # Dies bleibt, um sicherzustellen, dass das Skript ausführbar ist
          chmod +x gradlew
          echo "gradlew is now executable."
      
      # Entferne den "Regenerate Gradle Wrapper" Schritt,
      # da Codemagic dies normalerweise automatisch verwaltet.
      # Wenn die gradle-wrapper.properties korrekt sind,
      # sollte Codemagic die JAR selbst herunterladen.
      
      - name: Set Android SDK path # Dies ist eher zur Information und Pfadanpassung, nicht essentiell für den Wrapper-Download
        script: |
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $CM_ENV
          echo "PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools" >> $CM_ENV
      
      - name: Clean Project
        script: |
          # Codemagic erwartet, dass ./gradlew jetzt funktioniert
          ./gradlew clean
          echo "Project cleaned."
      
      - name: Build Android Release APK
        script: |
          ./gradlew assembleRelease
          echo "APK build complete."
          
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      
    publishing:
      email:
        recipients:
          - deine.email@example.com
