// app/src/main/java/com/MaFiSoft/BuyPal/ui/theme/Color.kt
// Stand: 2025-07-09_12:28:00, Codezeilen: ~300 (Vollständige Farbdefinitionen für alle Themes, RotTheme Fehler korrigiert)

package com.MaFiSoft.BuyPal.ui.theme

import androidx.compose.ui.graphics.Color

// #################################################################################################
// ######################################### BLAU THEME ############################################
// #################################################################################################
val BlauHellPrimary = Color(0xFF2196F3) // blue_500
val BlauHellOnPrimary = Color(0xFFFFFFFF) // white
val BlauHellPrimaryContainer = Color(0xFF90CAF9) // blue_200
val BlauHellOnPrimaryContainer = Color(0xFF1976D2) // blue_700
val BlauHellSecondary = Color(0xFF80CBC4) // teal_200
val BlauHellOnSecondary = Color(0xFF000000) // black
val BlauHellSecondaryContainer = Color(0xFFC8E6C9)
val BlauHellOnSecondaryContainer = Color(0xFF2E7D32)
val BlauHellTertiary = Color(0xFFBB86FC)
val BlauHellOnTertiary = Color(0xFF000000)
val BlauHellTertiaryContainer = Color(0xFFD0BCFF)
val BlauHellOnTertiaryContainer = Color(0xFF381E72)
val BlauHellError = Color(0xFFBA1A1A)
val BlauHellOnError = Color(0xFFFFFFFF)
val BlauHellErrorContainer = Color(0xFFFFDAD6)
val BlauHellOnErrorContainer = Color(0xFF410002)
val BlauHellBackground = Color(0xFFFFFFFF) // white
val BlauHellOnBackground = Color(0xFF000000) // black
val BlauHellSurface = Color(0xFFFFFFFF) // white
val BlauHellOnSurface = Color(0xFF000000) // black
val BlauHellSurfaceVariant = Color(0xFFBBDEFB)
val BlauHellOnSurfaceVariant = Color(0xFF424242)
val BlauHellOutline = Color(0xFF757575)
val BlauHellInverseOnSurface = Color(0xFFFFFFFF) // white
val BlauHellInverseSurface = Color(0xFF303030) // dark grey
val BlauHellInversePrimary = Color(0xFF90CAF9) // blue_200
val BlauHellSurfaceTint = Color(0xFF2196F3) // blue_500
val BlauHellOutlineVariant = Color(0xFFBDBDBD)
val BlauHellScrim = Color(0xFF000000)


val BlauDunkelPrimary = Color(0xFF90CAF9) // blue_200
val BlauDunkelOnPrimary = Color(0xFF1976D2) // blue_700
val BlauDunkelPrimaryContainer = Color(0xFF1976D2) // blue_700
val BlauDunkelOnPrimaryContainer = Color(0xFF90CAF9) // blue_200
val BlauDunkelSecondary = Color(0xFF80CBC4) // teal_200
val BlauDunkelOnSecondary = Color(0xFF000000) // black
val BlauDunkelSecondaryContainer = Color(0xFF4CAF50)
val BlauDunkelOnSecondaryContainer = Color(0xFFC8E6C9)
val BlauDunkelTertiary = Color(0xFFD0BCFF)
val BlauDunkelOnTertiary = Color(0xFF381E72)
val BlauDunkelTertiaryContainer = Color(0xFF4F378A)
val BlauDunkelOnTertiaryContainer = Color(0xFFEADDFF)
val BlauDunkelError = Color(0xFFFFB4AB)
val BlauDunkelOnError = Color(0xFF690005)
val BlauDunkelErrorContainer = Color(0xFF93000A)
val BlauDunkelOnErrorContainer = Color(0xFFFFDAD6)
val BlauDunkelBackground = Color(0xFF121212) // dark grey
val BlauDunkelOnBackground = Color(0xFFFFFFFF) // white
val BlauDunkelSurface = Color(0xFF121212) // dark grey
val BlauDunkelOnSurface = Color(0xFFFFFFFF) // white
val BlauDunkelSurfaceVariant = Color(0xFF424242)
val BlauDunkelOnSurfaceVariant = Color(0xFFBDBDBD)
val BlauDunkelOutline = Color(0xFF9E9E9E)
val BlauDunkelInverseOnSurface = Color(0xFF212121)
val BlauDunkelInverseSurface = Color(0xFFE0E0E0)
val BlauDunkelInversePrimary = Color(0xFF2196F3) // blue_500
val BlauDunkelSurfaceTint = Color(0xFF90CAF9) // blue_200
val BlauDunkelOutlineVariant = Color(0xFF424242)
val BlauDunkelScrim = Color(0xFF000000)

// #################################################################################################
// ######################################### ROT THEME #############################################
// #################################################################################################
val RotHellPrimary = Color(0xFFD32F2F) // red_700
val RotHellOnPrimary = Color(0xFFFFFFFF)
val RotHellPrimaryContainer = Color(0xFFFFCDD2) // red_100
val RotHellOnPrimaryContainer = Color(0xFFB71C1C) // red_900
val RotHellSecondary = Color(0xFFF48FB1) // pink_200
val RotHellOnSecondary = Color(0xFF000000)
val RotHellSecondaryContainer = Color(0xFFFFEBEE)
val RotHellOnSecondaryContainer = Color(0xFFC2185B)
val RotHellTertiary = Color(0xFFBB86FC) // KORREKTUR: Hier war ein Fehler, sollte auf Lila-Farben zeigen
val RotHellOnTertiary = Color(0xFF000000)
val RotHellTertiaryContainer = Color(0xFFD0BCFF)
val RotHellOnTertiaryContainer = Color(0xFF381E72)
val RotHellError = Color(0xFFBA1A1A)
val RotHellOnError = Color(0xFFFFFFFF)
val RotHellErrorContainer = Color(0xFFFFDAD6)
val RotHellOnErrorContainer = Color(0xFF410002)
val RotHellBackground = Color(0xFFFFFFFF)
val RotHellOnBackground = Color(0xFF000000)
val RotHellSurface = Color(0xFFFFFFFF)
val RotHellOnSurface = Color(0xFF000000)
val RotHellSurfaceVariant = Color(0xFFFFCDD2)
val RotHellOnSurfaceVariant = Color(0xFF757575)
val RotHellOutline = Color(0xFFBDBDBD)
val RotHellInverseOnSurface = Color(0xFF212121)
val RotHellInverseSurface = Color(0xFFE0E0E0)
val RotHellInversePrimary = Color(0xFFEF9A9A) // red_200
val RotHellSurfaceTint = Color(0xFFD32F2F)
val RotHellOutlineVariant = Color(0xFFE0E0E0)
val RotHellScrim = Color(0xFF000000)

val RotDunkelPrimary = Color(0xFFEF9A9A) // red_200
val RotDunkelOnPrimary = Color(0xFFB71C1C) // red_900
val RotDunkelPrimaryContainer = Color(0xFFB71C1C) // red_900
val RotDunkelOnPrimaryContainer = Color(0xFFEF9A9A) // red_200
val RotDunkelSecondary = Color(0xFFF48FB1)
val RotDunkelOnSecondary = Color(0xFF000000)
val RotDunkelSecondaryContainer = Color(0xFFC2185B)
val RotDunkelOnSecondaryContainer = Color(0xFFFFEBEE)
val RotDunkelTertiary = Color(0xFFD0BCFF) // KORREKTUR: Hier war ein Fehler, sollte auf Lila-Farben zeigen
val RotDunkelOnTertiary = Color(0xFF381E72)
val RotDunkelTertiaryContainer = Color(0xFF4F378A)
val RotDunkelOnTertiaryContainer = Color(0xFFEADDFF)
val RotDunkelError = Color(0xFFFFB4AB)
val RotDunkelOnError = Color(0xFF690005)
val RotDunkelErrorContainer = Color(0xFF93000A)
val RotDunkelOnErrorContainer = Color(0xFFFFDAD6)
val RotDunkelBackground = Color(0xFF121212)
val RotDunkelOnBackground = Color(0xFFFFFFFF)
val RotDunkelSurface = Color(0xFF121212)
val RotDunkelOnSurface = Color(0xFFFFFFFF)
val RotDunkelSurfaceVariant = Color(0xFF424242)
val RotDunkelOnSurfaceVariant = Color(0xFFBDBDBD)
val RotDunkelOutline = Color(0xFF9E9E9E)
val RotDunkelInverseOnSurface = Color(0xFF212121)
val RotDunkelInverseSurface = Color(0xFFE0E0E0)
val RotDunkelInversePrimary = Color(0xFFD32F2F)
val RotDunkelSurfaceTint = Color(0xFFEF9A9A)
val RotDunkelOutlineVariant = Color(0xFF424242)
val RotDunkelScrim = Color(0xFF000000)

// #################################################################################################
// ######################################### GRUEN THEME ###########################################
// #################################################################################################
val GruenHellPrimary = Color(0xFF4CAF50) // green_500
val GruenHellOnPrimary = Color(0xFFFFFFFF)
val GruenHellPrimaryContainer = Color(0xFFA5D6A7) // green_200
val GruenHellOnPrimaryContainer = Color(0xFF388E3C) // green_700
val GruenHellSecondary = Color(0xFFCDDC39) // lime_500
val GruenHellOnSecondary = Color(0xFF000000)
val GruenHellSecondaryContainer = Color(0xFFF0F4C3)
val GruenHellOnSecondaryContainer = Color(0xFF827717)
val GruenHellTertiary = Color(0xFF673AB7) // deep_purple_500
val GruenHellOnTertiary = Color(0xFFFFFFFF)
val GruenHellTertiaryContainer = Color(0xFFD1C4E9)
val GruenHellOnTertiaryContainer = Color(0xFF311B92)
val GruenHellError = Color(0xFFBA1A1A)
val GruenHellOnError = Color(0xFFFFFFFF)
val GruenHellErrorContainer = Color(0xFFFFDAD6)
val GruenHellOnErrorContainer = Color(0xFF410002)
val GruenHellBackground = Color(0xFFFFFFFF)
val GruenHellOnBackground = Color(0xFF000000)
val GruenHellSurface = Color(0xFFFFFFFF)
val GruenHellOnSurface = Color(0xFF000000)
val GruenHellSurfaceVariant = Color(0xFFC8E6C9)
val GruenHellOnSurfaceVariant = Color(0xFF757575)
val GruenHellOutline = Color(0xFFBDBDBD)
val GruenHellInverseOnSurface = Color(0xFF212121)
val GruenHellInverseSurface = Color(0xFFE0E0E0)
val GruenHellInversePrimary = Color(0xFFC8E6C9) // green_200
val GruenHellSurfaceTint = Color(0xFF4CAF50)
val GruenHellOutlineVariant = Color(0xFFE0E0E0)
val GruenHellScrim = Color(0xFF000000)

val GruenDunkelPrimary = Color(0xFFC8E6C9) // green_200
val GruenDunkelOnPrimary = Color(0xFF388E3C) // green_700
val GruenDunkelPrimaryContainer = Color(0xFF388E3C) // green_700
val GruenDunkelOnPrimaryContainer = Color(0xFFC8E6C9) // green_200
val GruenDunkelSecondary = Color(0xFFF0F4C3)
val GruenDunkelOnSecondary = Color(0xFF827717)
val GruenDunkelSecondaryContainer = Color(0xFFCDDC39)
val GruenDunkelOnSecondaryContainer = Color(0xFFF0F4C3)
val GruenDunkelTertiary = Color(0xFFD1C4E9)
val GruenDunkelOnTertiary = Color(0xFF311B92)
val GruenDunkelTertiaryContainer = Color(0xFF673AB7)
val GruenDunkelOnTertiaryContainer = Color(0xFFD1C4E9)
val GruenDunkelError = Color(0xFFFFB4AB)
val GruenDunkelOnError = Color(0xFF690005)
val GruenDunkelErrorContainer = Color(0xFF93000A)
val GruenDunkelOnErrorContainer = Color(0xFFFFDAD6)
val GruenDunkelBackground = Color(0xFF121212)
val GruenDunkelOnBackground = Color(0xFFFFFFFF)
val GruenDunkelSurface = Color(0xFF121212)
val GruenDunkelOnSurface = Color(0xFFFFFFFF)
val GruenDunkelSurfaceVariant = Color(0xFF424242)
val GruenDunkelOnSurfaceVariant = Color(0xFFBDBDBD)
val GruenDunkelOutline = Color(0xFF9E9E9E)
val GruenDunkelInverseOnSurface = Color(0xFF212121)
val GruenDunkelInverseSurface = Color(0xFFE0E0E0)
val GruenDunkelInversePrimary = Color(0xFF4CAF50)
val GruenDunkelSurfaceTint = Color(0xFFA5D6A7)
val GruenDunkelOutlineVariant = Color(0xFF424242)
val GruenDunkelScrim = Color(0xFF000000)

// #################################################################################################
// ######################################### LILA THEME ############################################
// #################################################################################################
val LilaHellPrimary = Color(0xFF673AB7) // deep_purple_500
val LilaHellOnPrimary = Color(0xFFFFFFFF)
val LilaHellPrimaryContainer = Color(0xFFD1C4E9) // deep_purple_100
val LilaHellOnPrimaryContainer = Color(0xFF311B92) // deep_purple_900
val LilaHellSecondary = Color(0xFF9C27B0) // purple_500
val LilaHellOnSecondary = Color(0xFFFFFFFF)
val LilaHellSecondaryContainer = Color(0xFFE1BEE7)
val LilaHellOnSecondaryContainer = Color(0xFF6A1B9A)
val LilaHellTertiary = Color(0xFF4CAF50) // KORREKTUR: Hier war ein Fehler, sollte auf Grün-Farben zeigen
val LilaHellOnTertiary = Color(0xFFFFFFFF)
val LilaHellTertiaryContainer = Color(0xFFA5D6A7)
val LilaHellOnTertiaryContainer = Color(0xFF388E3C)
val LilaHellError = Color(0xFFBA1A1A)
val LilaHellOnError = Color(0xFFFFFFFF)
val LilaHellErrorContainer = Color(0xFFFFDAD6)
val LilaHellOnErrorContainer = Color(0xFF410002)
val LilaHellBackground = Color(0xFFFFFFFF)
val LilaHellOnBackground = Color(0xFF000000)
val LilaHellSurface = Color(0xFFFFFFFF)
val LilaHellOnSurface = Color(0xFF000000)
val LilaHellSurfaceVariant = Color(0xFFE1BEE7)
val LilaHellOnSurfaceVariant = Color(0xFF757575)
val LilaHellOutline = Color(0xFFBDBDBD)
val LilaHellInverseOnSurface = Color(0xFF212121)
val LilaHellInverseSurface = Color(0xFFE0E0E0)
val LilaHellInversePrimary = Color(0xFFD1C4E9)
val LilaHellSurfaceTint = Color(0xFF673AB7)
val LilaHellOutlineVariant = Color(0xFFE0E0E0)
val LilaHellScrim = Color(0xFF000000)

val LilaDunkelPrimary = Color(0xFFD1C4E9)
val LilaDunkelOnPrimary = Color(0xFF311B92)
val LilaDunkelPrimaryContainer = Color(0xFF311B92)
val LilaDunkelOnPrimaryContainer = Color(0xFFD1C4E9)
val LilaDunkelSecondary = Color(0xFFE1BEE7)
val LilaDunkelOnSecondary = Color(0xFF6A1B9A)
val LilaDunkelSecondaryContainer = Color(0xFF9C27B0)
val LilaDunkelOnSecondaryContainer = Color(0xFFE1BEE7)
val LilaDunkelTertiary = Color(0xFFA5D6A7)
val LilaDunkelOnTertiary = Color(0xFF388E3C)
val LilaDunkelTertiaryContainer = Color(0xFF4CAF50)
val LilaDunkelOnTertiaryContainer = Color(0xFFA5D6A7)
val LilaDunkelError = Color(0xFFFFB4AB)
val LilaDunkelOnError = Color(0xFF690005)
val LilaDunkelErrorContainer = Color(0xFF93000A)
val LilaDunkelOnErrorContainer = Color(0xFFFFDAD6)
val LilaDunkelBackground = Color(0xFF121212)
val LilaDunkelOnBackground = Color(0xFFFFFFFF)
val LilaDunkelSurface = Color(0xFF121212)
val LilaDunkelOnSurface = Color(0xFFFFFFFF)
val LilaDunkelSurfaceVariant = Color(0xFF424242)
val LilaDunkelOnSurfaceVariant = Color(0xFFBDBDBD)
val LilaDunkelOutline = Color(0xFF9E9E9E)
val LilaDunkelInverseOnSurface = Color(0xFF212121)
val LilaDunkelInverseSurface = Color(0xFFE0E0E0)
val LilaDunkelInversePrimary = Color(0xFF673AB7)
val LilaDunkelSurfaceTint = Color(0xFFD1C4E9)
val LilaDunkelOutlineVariant = Color(0xFF424242)
val LilaDunkelScrim = Color(0xFF000000)

// #################################################################################################
// ######################################### ORANGE THEME ##########################################
// #################################################################################################
val OrangeHellPrimary = Color(0xFFFF9800) // orange_500
val OrangeHellOnPrimary = Color(0xFFFFFFFF)
val OrangeHellPrimaryContainer = Color(0xFFFFCC80) // orange_200
val OrangeHellOnPrimaryContainer = Color(0xFFEF6C00) // orange_700
val OrangeHellSecondary = Color(0xFFFFC107) // amber_500
val OrangeHellOnSecondary = Color(0xFF000000)
val OrangeHellSecondaryContainer = Color(0xFFFFECB3)
val OrangeHellOnSecondaryContainer = Color(0xFFFF8F00)
val OrangeHellTertiary = Color(0xFF795548) // brown_500
val OrangeHellOnTertiary = Color(0xFFFFFFFF)
val OrangeHellTertiaryContainer = Color(0xFFD7CCC8)
val OrangeHellOnTertiaryContainer = Color(0xFF3E2723)
val OrangeHellError = Color(0xFFBA1A1A)
val OrangeHellOnError = Color(0xFFFFFFFF)
val OrangeHellErrorContainer = Color(0xFFFFDAD6)
val OrangeHellOnErrorContainer = Color(0xFF410002)
val OrangeHellBackground = Color(0xFFFFFFFF)
val OrangeHellOnBackground = Color(0xFF000000)
val OrangeHellSurface = Color(0xFFFFFFFF)
val OrangeHellOnSurface = Color(0xFF000000)
val OrangeHellSurfaceVariant = Color(0xFFFFE0B2)
val OrangeHellOnSurfaceVariant = Color(0xFF757575)
val OrangeHellOutline = Color(0xFFBDBDBD)
val OrangeHellInverseOnSurface = Color(0xFF212121)
val OrangeHellInverseSurface = Color(0xFFE0E0E0)
val OrangeHellInversePrimary = Color(0xFFFFCC80)
val OrangeHellSurfaceTint = Color(0xFFFF9800)
val OrangeHellOutlineVariant = Color(0xFFE0E0E0)
val OrangeHellScrim = Color(0xFF000000)

val OrangeDunkelPrimary = Color(0xFFFFCC80)
val OrangeDunkelOnPrimary = Color(0xFFEF6C00)
val OrangeDunkelPrimaryContainer = Color(0xFFEF6C00)
val OrangeDunkelOnPrimaryContainer = Color(0xFFFFCC80)
val OrangeDunkelSecondary = Color(0xFFFFECB3)
val OrangeDunkelOnSecondary = Color(0xFFFF8F00)
val OrangeDunkelSecondaryContainer = Color(0xFFFFC107)
val OrangeDunkelOnSecondaryContainer = Color(0xFFFFECB3)
val OrangeDunkelTertiary = Color(0xFFD7CCC8)
val OrangeDunkelOnTertiary = Color(0xFF3E2723)
val OrangeDunkelTertiaryContainer = Color(0xFF795548)
val OrangeDunkelOnTertiaryContainer = Color(0xFFD7CCC8)
val OrangeDunkelError = Color(0xFFFFB4AB)
val OrangeDunkelOnError = Color(0xFF690005)
val OrangeDunkelErrorContainer = Color(0xFF93000A)
val OrangeDunkelOnErrorContainer = Color(0xFFFFDAD6)
val OrangeDunkelBackground = Color(0xFF121212)
val OrangeDunkelOnBackground = Color(0xFFFFFFFF)
val OrangeDunkelSurface = Color(0xFF121212)
val OrangeDunkelOnSurface = Color(0xFFFFFFFF)
val OrangeDunkelSurfaceVariant = Color(0xFF424242)
val OrangeDunkelOnSurfaceVariant = Color(0xFFBDBDBD)
val OrangeDunkelOutline = Color(0xFF9E9E9E)
val OrangeDunkelInverseOnSurface = Color(0xFF212121)
val OrangeDunkelInverseSurface = Color(0xFFE0E0E0)
val OrangeDunkelInversePrimary = Color(0xFFFF9800)
val OrangeDunkelSurfaceTint = Color(0xFFFFCC80)
val OrangeDunkelOutlineVariant = Color(0xFF424242)
val OrangeDunkelScrim = Color(0xFF000000)

// #################################################################################################
// ######################################### GRAU THEME ############################################
// #################################################################################################
val GrauHellPrimary = Color(0xFF607D8B) // blue_grey_500
val GrauHellOnPrimary = Color(0xFFFFFFFF)
val GrauHellPrimaryContainer = Color(0xFFB0BEC5) // blue_grey_200
val GrauHellOnPrimaryContainer = Color(0xFF37474F) // blue_grey_700
val GrauHellSecondary = Color(0xFF9E9E9E) // grey_500
val GrauHellOnSecondary = Color(0xFF000000)
val GrauHellSecondaryContainer = Color(0xFFE0E0E0)
val GrauHellOnSecondaryContainer = Color(0xFF424242)
val GrauHellTertiary = Color(0xFF78909C) // blue_grey_400
val GrauHellOnTertiary = Color(0xFFFFFFFF)
val GrauHellTertiaryContainer = Color(0xFFCFD8DC)
val GrauHellOnTertiaryContainer = Color(0xFF455A64)
val GrauHellError = Color(0xFFBA1A1A)
val GrauHellOnError = Color(0xFFFFFFFF)
val GrauHellErrorContainer = Color(0xFFFFDAD6)
val GrauHellOnErrorContainer = Color(0xFF410002)
val GrauHellBackground = Color(0xFFFFFFFF)
val GrauHellOnBackground = Color(0xFF000000)
val GrauHellSurface = Color(0xFFFFFFFF)
val GrauHellOnSurface = Color(0xFF000000)
val GrauHellSurfaceVariant = Color(0xFFE3E3E3)
val GrauHellOnSurfaceVariant = Color(0xFF757575)
val GrauHellOutline = Color(0xFFBDBDBD)
val GrauHellInverseOnSurface = Color(0xFF212121)
val GrauHellInverseSurface = Color(0xFFE0E0E0)
val GrauHellInversePrimary = Color(0xFFB0BEC5)
val GrauHellSurfaceTint = Color(0xFF607D8B)
val GrauHellOutlineVariant = Color(0xFFE0E0E0)
val GrauHellScrim = Color(0xFF000000)

val GrauDunkelPrimary = Color(0xFFB0BEC5)
val GrauDunkelOnPrimary = Color(0xFF37474F)
val GrauDunkelPrimaryContainer = Color(0xFF37474F)
val GrauDunkelOnPrimaryContainer = Color(0xFFB0BEC5)
val GrauDunkelSecondary = Color(0xFFE0E0E0)
val GrauDunkelOnSecondary = Color(0xFF424242)
val GrauDunkelSecondaryContainer = Color(0xFF9E9E9E)
val GrauDunkelOnSecondaryContainer = Color(0xFFE0E0E0)
val GrauDunkelTertiary = Color(0xFFCFD8DC)
val GrauDunkelOnTertiary = Color(0xFF455A64)
val GrauDunkelTertiaryContainer = Color(0xFF78909C)
val GrauDunkelOnTertiaryContainer = Color(0xFFCFD8DC)
val GrauDunkelError = Color(0xFFFFB4AB)
val GrauDunkelOnError = Color(0xFF690005)
val GrauDunkelErrorContainer = Color(0xFF93000A)
val GrauDunkelOnErrorContainer = Color(0xFFFFDAD6)
val GrauDunkelBackground = Color(0xFF121212)
val GrauDunkelOnBackground = Color(0xFFFFFFFF)
val GrauDunkelSurface = Color(0xFF121212)
val GrauDunkelOnSurface = Color(0xFFFFFFFF)
val GrauDunkelSurfaceVariant = Color(0xFF424242)
val GrauDunkelOnSurfaceVariant = Color(0xFFBDBDBD)
val GrauDunkelOutline = Color(0xFF9E9E9E)
val GrauDunkelInverseOnSurface = Color(0xFF212121)
val GrauDunkelInverseSurface = Color(0xFFE0E0E0)
val GrauDunkelInversePrimary = Color(0xFF607D8B)
val GrauDunkelSurfaceTint = Color(0xFFB0BEC5)
val GrauDunkelOutlineVariant = Color(0xFF424242)
val GrauDunkelScrim = Color(0xFF000000)

// #################################################################################################
// ######################################### TUERKIS THEME #########################################
// #################################################################################################
val TuerkisHellPrimary = Color(0xFF009688) // teal_500
val TuerkisHellOnPrimary = Color(0xFFFFFFFF)
val TuerkisHellPrimaryContainer = Color(0xFF80CBC4) // teal_200
val TuerkisHellOnPrimaryContainer = Color(0xFF00695C) // teal_700
val TuerkisHellSecondary = Color(0xFF4DD0E1) // cyan_300
val TuerkisHellOnSecondary = Color(0xFF000000)
val TuerkisHellSecondaryContainer = Color(0xFFB2EBF2)
val TuerkisHellOnSecondaryContainer = Color(0xFF00838F)
val TuerkisHellTertiary = Color(0xFF26A69A) // teal_400
val TuerkisHellOnTertiary = Color(0xFFFFFFFF)
val TuerkisHellTertiaryContainer = Color(0xFF80DEEA)
val TuerkisHellOnTertiaryContainer = Color(0xFF00796B)
val TuerkisHellError = Color(0xFFBA1A1A)
val TuerkisHellOnError = Color(0xFFFFFFFF)
val TuerkisHellErrorContainer = Color(0xFFFFDAD6)
val TuerkisHellOnErrorContainer = Color(0xFF410002)
val TuerkisHellBackground = Color(0xFFFFFFFF)
val TuerkisHellOnBackground = Color(0xFF000000)
val TuerkisHellSurface = Color(0xFFFFFFFF)
val TuerkisHellOnSurface = Color(0xFF000000)
val TuerkisHellSurfaceVariant = Color(0xFFE0F2F1)
val TuerkisHellOnSurfaceVariant = Color(0xFF757575)
val TuerkisHellOutline = Color(0xFFBDBDBD)
val TuerkisHellInverseOnSurface = Color(0xFF212121)
val TuerkisHellInverseSurface = Color(0xFFE0E0E0)
val TuerkisHellInversePrimary = Color(0xFF80CBC4)
val TuerkisHellSurfaceTint = Color(0xFF009688)
val TuerkisHellOutlineVariant = Color(0xFFE0E0E0)
val TuerkisHellScrim = Color(0xFF000000)

val TuerkisDunkelPrimary = Color(0xFF80CBC4)
val TuerkisDunkelOnPrimary = Color(0xFF00695C)
val TuerkisDunkelPrimaryContainer = Color(0xFF00695C)
val TuerkisDunkelOnPrimaryContainer = Color(0xFF80CBC4)
val TuerkisDunkelSecondary = Color(0xFFB2EBF2)
val TuerkisDunkelOnSecondary = Color(0xFF00838F)
val TuerkisDunkelSecondaryContainer = Color(0xFF4DD0E1)
val TuerkisDunkelOnSecondaryContainer = Color(0xFFB2EBF2)
val TuerkisDunkelTertiary = Color(0xFF80DEEA)
val TuerkisDunkelOnTertiary = Color(0xFF00796B)
val TuerkisDunkelTertiaryContainer = Color(0xFF26A69A)
val TuerkisDunkelOnTertiaryContainer = Color(0xFF80DEEA)
val TuerkisDunkelError = Color(0xFFFFB4AB)
val TuerkisDunkelOnError = Color(0xFF690005)
val TuerkisDunkelErrorContainer = Color(0xFF93000A)
val TuerkisDunkelOnErrorContainer = Color(0xFFFFDAD6)
val TuerkisDunkelBackground = Color(0xFF121212)
val TuerkisDunkelOnBackground = Color(0xFFFFFFFF)
val TuerkisDunkelSurface = Color(0xFF121212)
val TuerkisDunkelOnSurface = Color(0xFFFFFFFF)
val TuerkisDunkelSurfaceVariant = Color(0xFF424242)
val TuerkisDunkelOnSurfaceVariant = Color(0xFFBDBDBD)
val TuerkisDunkelOutline = Color(0xFF9E9E9E)
val TuerkisDunkelInverseOnSurface = Color(0xFF212121)
val TuerkisDunkelInverseSurface = Color(0xFFE0E0E0)
val TuerkisDunkelInversePrimary = Color(0xFF009688)
val TuerkisDunkelSurfaceTint = Color(0xFF80CBC4)
val TuerkisDunkelOutlineVariant = Color(0xFF424242)
val TuerkisDunkelScrim = Color(0xFF000000)
